# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

name : Docker-CI
trigger:
  branches:
    include:
      - master

 
pool:
  vmImage: 'ubuntu-latest'
 
variables:
  ImageName: '173129/adservice:$(Build.BuildId)'
 
stages:
- stage: Sonar
  jobs:
  - job: Sonar
    steps:
    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'sonarqube'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'adservice'
        cliProjectName: 'adservice'
        cliSources: 'src/main'
   # - task: SonarQubeAnalyze@4
     # displayName: 'Run SonarQube Scan'

    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'
    

      
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
    steps:
    - task: Docker@1
      displayName: 'Build the Docker image'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: 'Build an image'
        dockerFile: '**/Dockerfile'
        imageName: '$(ImageName)'
        includeLatestTag: true
        useDefaultContext: false
        buildContext: '.'
        addBaseImageData: 
        addDefaultLabels: 
 
    - task: Docker@1
      displayName: 'Push the Docker image to Dockerhub'
      inputs:
        containerregistrytype: 'Container Registry'

        dockerRegistryEndpoint: 'Docker Hub'
        command: 'Push an image'
        imageName: '$(ImageName)'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    
 
    
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/TEST-*.xml'
        mergeTestResults: true
        testRunTitle: 'adservice'
    - task: HelmInstaller@0
      inputs:
        helmVersion: '2.14.1'
        installKubectl: true
  
    - task: HelmDeploy@0
      inputs:
        command: 'package'
        chartPath: 'chart path'
        chartVersion: 'Build.BuildNumber'
        
    - task: HelmDeploy@0
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceConnection: 'kubernetes'
        namespace: 'default'
        command: 'upgrade'
        chartType: 'FilePath'
        chartPath: 'ChartPackage'
        releaseName: 'khushboo'